In [1]:
# Research compressive strength testing
# Import the .csv and convert to NumPy array

import pandas as pd
import numpy as np


# Make NumPy values easier to read
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

names = ["Cement", "Aggregate", "FA", "Cyclodextrin", "Water", "Days", "Load 1", "Comp 1", "Load 2", "Comp 2", "Load 3", "Comp 3"]

compressive_dataset = pd.read_csv(
    '/content/drive/MyDrive/1 Projects/3_4 Research Project/Research data/compressive_all_data.csv', 
    names = ["Cement", "Sand", "Aggregate", "FA", "Cyclodextrin", "Water", "Days", "Comp 1", "Comp 2", "Comp 3"])

data_arr = compressive_dataset.to_numpy()

np.random.shuffle(data_arr)

X_values = data_arr[:,:7]
# print(X_values)
y_values = data_arr[:,8:9]
# print(y_values)

# 1. Create the model
model_1 = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model_1.compile(loss=tf.keras.losses.mae,
                optimizer=tf.keras.optimizers.SGD(),
                metrics=["mae"])

# 3. Fit the model
model_1.fit(tf.expand_dims(X_values, axis=-1), y_values, epochs=100, verbose=0)


In [2]:
model_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7, 1)              2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [4]:
y_preds_1 = model_1.predict(X_values)

mae_1 = tf.metrics.mean_absolute_error(y_true=y_values,
                                     y_pred=tf.squeeze(y_preds_1))

mse_1 = tf.metrics.mean_squared_error(y_true=y_values,
                                     y_pred=tf.squeeze(y_preds_1))

mae_1, mse_1

(<tf.Tensor: shape=(120,), dtype=float32, numpy=
 array([300.806, 323.867, 296.133, 350.857, 322.667, 321.635, 382.414,
        330.733, 360.125, 311.267, 310.134, 305.234, 384.714, 377.347,
        340.034, 316.635, 340.934, 310.533, 334.223, 308.034, 311.733,
        328.168, 320.734, 376.147, 305.367, 300.823, 344.779, 361.047,
        381.147, 378.847, 321.334, 340.084, 331.533, 368.414, 339.034,
        329.233, 322.078, 363.423, 311.233, 310.595, 343.236, 360.857,
        338.123, 357.657, 338.496, 351.335, 369.723, 336.513, 335.135,
        315.424, 307.206, 294.233, 367.123, 332.434, 341.223, 388.514,
        338.734, 326.867, 352.435, 346.768, 345.568, 366.723, 337.268,
        347.268, 339.667, 361.057, 320.034, 325.795, 376.147, 377.815,
        369.314, 298.433, 323.334, 313.067, 311.468, 339.423, 387.514,
        312.533, 306.934, 320.535, 364.603, 384.214, 367.723, 304.267,
        347.335, 379.358, 325.967, 353.235, 336.135, 334.357, 297.133,
        354.257, 337.179, 32

In [10]:
print(y_values)

[[21. ]
 [41.5]
 [24.4]
 [59. ]
 [39.5]
 [47.5]
 [90.9]
 [59. ]
 [69.8]
 [28.9]
 [37.6]
 [32.7]
 [93.2]
 [75.2]
 [67.5]
 [42.5]
 [68.4]
 [38.8]
 [53. ]
 [35.5]
 [40. ]
 [43.4]
 [46.6]
 [74. ]
 [22.2]
 [20. ]
 [60. ]
 [58.9]
 [79. ]
 [76.7]
 [48.8]
 [50.8]
 [59.8]
 [76.9]
 [66.5]
 [57.5]
 [39.7]
 [82.2]
 [39.5]
 [30. ]
 [60. ]
 [69. ]
 [56.9]
 [65.8]
 [49.2]
 [77.2]
 [88.5]
 [46.2]
 [61. ]
 [32.2]
 [26.6]
 [22.5]
 [85.9]
 [60.7]
 [60. ]
 [97. ]
 [66.2]
 [43.7]
 [78.3]
 [62. ]
 [60.8]
 [85.5]
 [52.5]
 [62.5]
 [56.5]
 [69.2]
 [47.5]
 [43.6]
 [74. ]
 [77.2]
 [77.8]
 [26.7]
 [50.8]
 [30.7]
 [26.7]
 [58.2]
 [96. ]
 [40.8]
 [34.4]
 [39.7]
 [64. ]
 [92.7]
 [86.5]
 [21.9]
 [73.2]
 [77.2]
 [43.6]
 [79.1]
 [62. ]
 [42.5]
 [25.4]
 [62.4]
 [54. ]
 [48.5]
 [39.2]
 [22.2]
 [66.1]
 [69.8]
 [57.8]
 [53.4]
 [91. ]
 [72.5]
 [87. ]
 [69. ]
 [69.5]
 [47.1]
 [85.5]
 [15.5]
 [47.5]
 [54. ]
 [69. ]
 [64. ]
 [25.7]
 [79. ]
 [45.6]
 [85.9]
 [56.2]
 [94.5]
 [87.8]
 [49.1]]


In [12]:
print(X_values)

[[ 225.   720.  1076.   224.6    0.5  202.5    7. ]
 [ 450.   720.  1076.     0.     0.   225.     7. ]
 [ 260.   650.  1000.   260.     0.   208.     7. ]
 [ 315.   720.  1076.   135.     0.   225.    90. ]
 [ 315.   720.  1076.   135.     0.   225.    14. ]
 [ 260.   650.  1000.   259.5    0.5  208.    28. ]
 [ 520.   650.  1000.     0.     0.   208.   180. ]
 [ 519.9  650.  1000.     0.     0.1  208.     7. ]
 [ 315.   720.  1076.   134.6    0.5  211.5   90. ]
 [ 315.   720.  1076.   134.8    0.2  225.     7. ]
 [ 260.   650.  1000.   259.7    0.3  208.    14. ]
 [ 260.   650.  1000.   260.     0.   208.    14. ]
 [ 364.   650.  1000.   156.     0.   208.   180. ]
 [ 450.   720.  1076.     0.     0.   225.   180. ]
 [ 519.5  650.  1000.     0.     0.5  208.    14. ]
 [ 260.   650.  1000.   260.     0.   208.    28. ]
 [ 519.7  650.  1000.     0.     0.3  208.    14. ]
 [ 364.   650.  1000.   156.     0.   208.     7. ]
 [ 260.   650.  1000.   260.     0.   208.    90. ]
 [ 260.   65

In [11]:
print(data_arr)

[[ 225.   720.  1076.  ...   21.5   21.    21.1]
 [ 450.   720.  1076.  ...   39.6   41.5   41.6]
 [ 260.   650.  1000.  ...   24.4   24.4   25. ]
 ...
 [ 364.   650.  1000.  ...   95.2   94.5   94.3]
 [ 364.   650.  1000.  ...   88.    87.8   87.4]
 [ 315.   720.  1076.  ...   48.7   49.1   49.3]]
